name: Build (Pull Request)

on:
  pull_request_review:
    types:
      - submitted
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    if: |
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'maven'
      - name: Run Maven build
        run: ./mvnw --batch-mode -P ci clean verify -Dsnapshots.update-policy=always
